export enum ErrorCode {
  // --- Errores Genéricos (Infraestructura y Servidor) ---
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT",
  DATABASE_ERROR = "DATABASE_ERROR",

  // --- Errores de Petición (Cliente) ---
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MALFORMED_JSON = "MALFORMED_JSON",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

  // --- Autenticación y Autorización ---
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_INVALID = "TOKEN_INVALID",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",

  // --- Gestión de Recursos (Dominio) ---
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  RESOURCE_LOCKED = "RESOURCE_LOCKED",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",

  // --- Lógica de Negocio Específica ---
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  LIMIT_EXCEEDED = "LIMIT_EXCEEDED",
  INVALID_OPERATION = "INVALID_OPERATION",

  // --- Integraciones Externas ---
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  THIRD_PARTY_TIMEOUT = "THIRD_PARTY_TIMEOUT",

  // --- Estado de Cuenta y Registro ---
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  SESSION_LIMIT_REACHED = "SESSION_LIMIT_REACHED",

  // --- Suscripciones y Pagos (SaaS Level) ---
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",
  FEATURE_NOT_AVAILABLE = "FEATURE_NOT_AVAILABLE",

  // --- Almacenamiento y Archivos ---
  STORAGE_QUOTA_EXCEEDED = "STORAGE_QUOTA_EXCEEDED",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  VIRUS_DETECTED = "VIRUS_DETECTED",

  // --- Seguridad y Rate Limiting ---
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  IP_BLOCKED = "IP_BLOCKED",
  MFA_REQUIRED = "MFA_REQUIRED",
}
